GET http://localhost:4004/CatalogService/$metadata

###

GET http://localhost:4004/CatalogService/EmployeeSet?$top=2

###

POST http://localhost:4004/CatalogService/EmployeeSet
Content-Type: application/json

{
"nameFirst":"Minakshi",
"nameMiddle":null,
"nameLast":"Singh",
"nameInitials":null,
"sex":"F",
"language":"E",
"email":"mina@gmail.com",
"loginName":"SPMINAK"
}

###

PATCH  http://localhost:4004/CatalogService/EmployeeSet/c6909e3d-5899-4baa-9308-9f93f371c7b6
Content-Type: application/json

{
    "salaryAmount" : "9000000",
    "Currency_code" : "INR"
}

####

POST http://localhost:4004/mydemoservice/InsertEmployeeSrv
Content-Type: application/json

{
"nameFirst":"Minakshi011",
"nameMiddle":null,
"nameLast":"Singh",
"nameInitials":null,
"sex":"F",
"language":"E",
"email":"mina@gmail.com",
"loginName":"SPMINAK"
}

####

PUT  http://localhost:4004/mydemoservice/UpdateEmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C198A7FB
Content-Type: application/json

{
"nameFirst":"Minakshi008"

}

####

DELETE http://localhost:4004/mydemoservice/UpdateEmployeeSrv/50d90ae5-5ef3-4f65-b4b2-da31cf9b7665

###

GET http://localhost:4004/CatalogService/POs?$top=5

##### calling custom actions for the entity

POST http://localhost:4004/CatalogService/POs(02BD2137-0890-1EEA-A6C2-BB55C1978999)/CatalogService.boost
Content-Type: application/json

{}

###
GET http://localhost:4004/CatalogService/POs(02BD2137-0890-1EEA-A6C2-BB55C1978999)

###
GET http://localhost:4004/CatalogService/POs(02BD2137-0890-1EEA-A6C2-BB55C1978999)/CatalogService.largestOrder()

###
GET http://localhost:4004/v2/CatalogService/POs(02BD2137-0890-1EEA-A6C2-BB55C1978999)

##### calling custom actions for the entity with odata v2 model

POST http://localhost:4004/v2/CatalogService/POs_boost?ID=02BD2137-0890-1EEA-A6C2-BB55C1978999
Content-Type: application/json

{}

###
GET http://localhost:4004/v2/CatalogService/POs_largestOrder?ID=02BD2137-0890-1EEA-A6C2-BB55C1978999

####### Check with Security configuration

GET http://localhost:4004/CatalogService/EmployeeSet
Authorization: Basic rishi:1234
